-- CreateEnum
CREATE TYPE "STATUS" AS ENUM ('ANSWERED', 'NOT_ANSWERED', 'WITH_SHAYKH');

-- AlterTable
ALTER TABLE "QuestionAndAnswer" ADD COLUMN     "status" "STATUS" NOT NULL DEFAULT 'NOT_ANSWERED';
